Step 1:Initial setup
vhoreho/nextjs pull request #1
Opened 2022-08-01 20:54 UTC by vhoreho

2022-08-02 06:54 UTC, Ilya-Valasiuk requested changes

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/ActiveLink.tsx
> +// @ts-ignore
why we need ts-ignore?

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/ActiveLink.tsx
> +import React, { useState, useEffect, ReactElement, Children } from 'react'
please import react first in order

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/ActiveLink.tsx
> +const ActiveLink = ({
```
const ActiveLink: FunctionalComponent<Props> = ({ activeClassName, ...props }) => {
```

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/ActiveLink.tsx
> +export default ActiveLink
no default exports please - https://docs.google.com/document/d/1ez__g_pUi-T5aRnsBxumdu-stTuk6xZ6PtZroAd5BeY/edit#heading=h.e56r2bqdnrmg

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/Header/Burger.tsx
> +        <button className={`${styles.button} ${open ? 'active' : ''}`} onClick={() => setOpen(!open)}>
use [classnames](https://www.npmjs.com/package/classnames) lib

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/Header/Menu.tsx
> +// @ts-ignore
?

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/Header/Menu.tsx
> +import styles from '../../styles/components/header/Menu.module.scss';
https://docs.google.com/document/d/1b1Bt3sM4cKvmYgmNka41vWqeHzUZ4no2Jnb5tjZxd10/edit#

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on components/layout.tsx
> +export default function Layout({children}: {children:ReactNode}) {
do we need layout here or we can use just `_app.tsx`?

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on package.json
> +    "@types/uuid": "^8.3.4",
why types in dependencies?

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on pages/api/hello.js
> +export default function handler(req, res) {
do we need this?

2022-08-02 06:54 UTC, Ilya-Valasiuk commented on tsconfig.json
> +  },
please use absolute imports and place all code to `src` folder - https://nextjs.org/docs/advanced-features/module-path-aliases

2022-08-02 07:16 UTC, vhoreho commented on components/ActiveLink.tsx
> +// @ts-ignore
WebStorm linter swears

2022-08-02 07:16 UTC, vhoreho commented on components/ActiveLink.tsx
> +import React, { useState, useEffect, ReactElement, Children } from 'react'
Done

2022-08-02 07:22 UTC, vhoreho commented on components/ActiveLink.tsx
> +const ActiveLink = ({
Done

2022-08-02 08:11 UTC, vhoreho commented on pages/api/hello.js
> +export default function handler(req, res) {
Done

2022-08-02 08:16 UTC, vhoreho commented on tsconfig.json
> +  },
done

2022-08-02 08:16 UTC, vhoreho commented on package.json
> +    "@types/uuid": "^8.3.4",
done

2022-08-02 08:17 UTC, vhoreho commented on components/Header/Menu.tsx
> +import styles from '../../styles/components/header/Menu.module.scss';
done

2022-08-02 08:17 UTC, vhoreho commented on components/Header/Menu.tsx
> +// @ts-ignore
Deleted

2022-08-02 08:17 UTC, vhoreho commented on components/Header/Burger.tsx
> +        <button className={`${styles.button} ${open ? 'active' : ''}`} onClick={() => setOpen(!open)}>
Done

2022-08-02 08:20 UTC, vhoreho commented on components/ActiveLink.tsx
> +export default ActiveLink
done

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/layout/Layout.tsx
> +export function Layout({children}: {children:ReactNode}) {
not needed

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/utils/fetcher.ts
> +    const response = await fetch(`https://api.nytimes.com/svc/topstories/v2/${category}.json?api-key=ZGnYeMXFe2qj5uVKnmdIF36750qfoiG0`);
api token should be in env

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/utils/fetcher.ts
> +    const response = await fetch(`https://api.nytimes.com/svc/topstories/v2/${category}.json?api-key=ZGnYeMXFe2qj5uVKnmdIF36750qfoiG0`);
api path should be in constants/api.ts file

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/utils/fetcher.ts
> +    const data = await response.json();
try/catch

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/layout/header/burger/Burger.module.scss
> +@import '../../../../styles/mixins';
@import 'styles/mixins';

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/layout/header/Header.module.scss
> +@import "../../../styles/variables";
file name `styles.module.scss`

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/layout/header/Header.module.scss
> +@import "../../../styles/mixins";
@import "styles/mixins";

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/layout/header/Header.module.scss
> +  background: #FBFBFB;
all colors, all shadows should be in `styles/variables.scss`

2022-08-03 07:23 UTC, Ilya-Valasiuk commented on src/components/ActiveLink.tsx
> +import React, {useState, useEffect, ReactElement, Children, FunctionComponent} from 'react'
`components/common/active-link/ActiveLink.tsx`;

2022-08-04 07:16 UTC, Ilya-Valasiuk requested changes

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +  color: #7A7A7A;
colors and shadows should be from `styles/variables`

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +  border-top: 1px solid #D1D1D1;
the same here

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +  color: #161616;
the same

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +    margin: 1.5rem 0;
is there reason why we mix rem with px ?

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +    fill: #7A7A7A;
the same

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/footer/styles.module.scss
> +    fill: #161616;
the same

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +import {ActiveLink} from "../active-link/ActiveLink";
* formatting
* absolute path

```
import { ActiveLink } from "components/common/active-link/ActiveLink";
```

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +import logo from '../../../../public/logo.svg';
import order, absolute import ...

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/burger/Burger.tsx
> +import classNames from "classnames";
this should be in `common/header/components/burger/...`

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/burger/styles.module.scss
> +    background: #161616;
variable

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/burger/styles.module.scss
> +    width: 2rem;
rem with px, please use 1 approach

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/burger/styles.module.scss
> +    background: #ffffff;
variable

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/Header.tsx
> +                <ActiveLink href="/" activeClassName={styles.active}>
Why we need `ActiveLink` at all?

Why we can't define what is active here and do something like this `<Link className={isActive ? "styles.active" : ""}`

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/burger/Burger.tsx
> +    const btnClass = classNames(styles.button, {
do we need this variable at all? 

```
<button className={classNames(styles.button, { 'active': isOpen })} onClick={() => setOpen(!open)}>
```

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/styles.module.scss
> +  background: #FBFBFB;
variable

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/components/common/header/styles.module.scss
> +  box-shadow: 0 2px 10px rgba(22, 22, 22, 0.1);
variable

2022-08-04 07:16 UTC, Ilya-Valasiuk commented on src/constants/api.ts
> +export const API_URL:string = 'https://api.nytimes.com/svc/topstories/v2';
you do not need to cast variable to string as it already string.

+ it should come from `process.env.BASE_PATH` variable.

2022-08-05 08:06 UTC, Ilya-Valasiuk approved these changes

2022-08-05 09:25 UTC, merged